name: nleis
channels:
  - defaults
dependencies:
  - python=3
  - pip

  - pip:
    - matplotlib
    - jupyterlab 
    - numpy
    - altair
    - pandas
    - scipy
    - SALib
    - tqdm
    - tabulate

    
