name: nleis
channels:
  - defaults
dependencies:
  - python>=3.8,<3.14
  - pip

  - pip:
    - matplotlib
    - jupyterlab 
    - numpy
    - altair
    - pandas
    - scipy
    - SALib
    - tqdm
    - tabulate
    - impedance
    - networkx
    - joblib
    - threadpoolctl

    
